/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CodeRouteImport } from './routes/code'
import { Route as WordsRouteRouteImport } from './routes/words/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordsIndexRouteImport } from './routes/words/index'
import { Route as WordsRssDotxmlRouteImport } from './routes/words/rss[.]xml'
import { Route as WordsLibraryRouteImport } from './routes/words/library'
import { Route as WordsAboutRouteImport } from './routes/words/about'
import { Route as WordsStoryIdIndexRouteImport } from './routes/words/$storyId/index'
import { Route as WordsStoryIdChapterIdRouteImport } from './routes/words/$storyId/$chapterId'

const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsRouteRoute = WordsRouteRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsIndexRoute = WordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WordsRouteRoute,
} as any)
const WordsRssDotxmlRoute = WordsRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => WordsRouteRoute,
} as any)
const WordsLibraryRoute = WordsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => WordsRouteRoute,
} as any)
const WordsAboutRoute = WordsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WordsRouteRoute,
} as any)
const WordsStoryIdIndexRoute = WordsStoryIdIndexRouteImport.update({
  id: '/$storyId/',
  path: '/$storyId/',
  getParentRoute: () => WordsRouteRoute,
} as any)
const WordsStoryIdChapterIdRoute = WordsStoryIdChapterIdRouteImport.update({
  id: '/$storyId/$chapterId',
  path: '/$storyId/$chapterId',
  getParentRoute: () => WordsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/words': typeof WordsRouteRouteWithChildren
  '/code': typeof CodeRoute
  '/words/about': typeof WordsAboutRoute
  '/words/library': typeof WordsLibraryRoute
  '/words/rss.xml': typeof WordsRssDotxmlRoute
  '/words/': typeof WordsIndexRoute
  '/words/$storyId/$chapterId': typeof WordsStoryIdChapterIdRoute
  '/words/$storyId/': typeof WordsStoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/words/about': typeof WordsAboutRoute
  '/words/library': typeof WordsLibraryRoute
  '/words/rss.xml': typeof WordsRssDotxmlRoute
  '/words': typeof WordsIndexRoute
  '/words/$storyId/$chapterId': typeof WordsStoryIdChapterIdRoute
  '/words/$storyId': typeof WordsStoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/words': typeof WordsRouteRouteWithChildren
  '/code': typeof CodeRoute
  '/words/about': typeof WordsAboutRoute
  '/words/library': typeof WordsLibraryRoute
  '/words/rss.xml': typeof WordsRssDotxmlRoute
  '/words/': typeof WordsIndexRoute
  '/words/$storyId/$chapterId': typeof WordsStoryIdChapterIdRoute
  '/words/$storyId/': typeof WordsStoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/words'
    | '/code'
    | '/words/about'
    | '/words/library'
    | '/words/rss.xml'
    | '/words/'
    | '/words/$storyId/$chapterId'
    | '/words/$storyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code'
    | '/words/about'
    | '/words/library'
    | '/words/rss.xml'
    | '/words'
    | '/words/$storyId/$chapterId'
    | '/words/$storyId'
  id:
    | '__root__'
    | '/'
    | '/words'
    | '/code'
    | '/words/about'
    | '/words/library'
    | '/words/rss.xml'
    | '/words/'
    | '/words/$storyId/$chapterId'
    | '/words/$storyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WordsRouteRoute: typeof WordsRouteRouteWithChildren
  CodeRoute: typeof CodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/': {
      id: '/words/'
      path: '/'
      fullPath: '/words/'
      preLoaderRoute: typeof WordsIndexRouteImport
      parentRoute: typeof WordsRouteRoute
    }
    '/words/rss.xml': {
      id: '/words/rss.xml'
      path: '/rss.xml'
      fullPath: '/words/rss.xml'
      preLoaderRoute: typeof WordsRssDotxmlRouteImport
      parentRoute: typeof WordsRouteRoute
    }
    '/words/library': {
      id: '/words/library'
      path: '/library'
      fullPath: '/words/library'
      preLoaderRoute: typeof WordsLibraryRouteImport
      parentRoute: typeof WordsRouteRoute
    }
    '/words/about': {
      id: '/words/about'
      path: '/about'
      fullPath: '/words/about'
      preLoaderRoute: typeof WordsAboutRouteImport
      parentRoute: typeof WordsRouteRoute
    }
    '/words/$storyId/': {
      id: '/words/$storyId/'
      path: '/$storyId'
      fullPath: '/words/$storyId/'
      preLoaderRoute: typeof WordsStoryIdIndexRouteImport
      parentRoute: typeof WordsRouteRoute
    }
    '/words/$storyId/$chapterId': {
      id: '/words/$storyId/$chapterId'
      path: '/$storyId/$chapterId'
      fullPath: '/words/$storyId/$chapterId'
      preLoaderRoute: typeof WordsStoryIdChapterIdRouteImport
      parentRoute: typeof WordsRouteRoute
    }
  }
}

interface WordsRouteRouteChildren {
  WordsAboutRoute: typeof WordsAboutRoute
  WordsLibraryRoute: typeof WordsLibraryRoute
  WordsRssDotxmlRoute: typeof WordsRssDotxmlRoute
  WordsIndexRoute: typeof WordsIndexRoute
  WordsStoryIdChapterIdRoute: typeof WordsStoryIdChapterIdRoute
  WordsStoryIdIndexRoute: typeof WordsStoryIdIndexRoute
}

const WordsRouteRouteChildren: WordsRouteRouteChildren = {
  WordsAboutRoute: WordsAboutRoute,
  WordsLibraryRoute: WordsLibraryRoute,
  WordsRssDotxmlRoute: WordsRssDotxmlRoute,
  WordsIndexRoute: WordsIndexRoute,
  WordsStoryIdChapterIdRoute: WordsStoryIdChapterIdRoute,
  WordsStoryIdIndexRoute: WordsStoryIdIndexRoute,
}

const WordsRouteRouteWithChildren = WordsRouteRoute._addFileChildren(
  WordsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WordsRouteRoute: WordsRouteRouteWithChildren,
  CodeRoute: CodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
